# Generated by Django 3.0.7 on 2020-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('T_document', models.CharField(choices=[('Cedula', 'Cedula'), ('Cedula Extranjeria', 'Cedula Extranjeria'), ('Pasaporte', 'Pasaporte')], max_length=18, verbose_name='Tipo documento')),
                ('document', models.IntegerField(unique=True, verbose_name='Documento')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('cel', models.IntegerField(verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
