# Generated by Django 3.0.7 on 2020-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo electronico'),
        ),
    ]
