# Generated by Django 3.0.7 on 2020-07-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200725_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado/Activo'),
        ),
    ]
