# Generated by Django 3.0.7 on 2020-07-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_employee_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
