# Generated by Django 3.0.7 on 2020-08-04 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20200731_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='consecutivo',
            field=models.UUIDField(default=uuid.UUID('9227a9a7-bd95-4b19-9945-a3215c96d28d'), editable=False, unique=True),
        ),
    ]
