# Generated by Django 3.0.7 on 2020-08-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipping_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='consecutivo',
            field=models.CharField(default='21499462-0', max_length=11),
        ),
    ]
