# Generated by Django 3.0.7 on 2020-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20200804_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='consecutivo',
            field=models.CharField(default='3f422ad9c853', max_length=13),
        ),
    ]
