# Generated by Django 3.0.7 on 2020-08-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20200805_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='c_cel',
            field=models.CharField(max_length=30, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='c_document',
            field=models.CharField(max_length=100, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='c_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='consecutivo',
            field=models.CharField(default='e6e327b3416a', max_length=13),
        ),
    ]
