# Generated by Django 3.0.7 on 2020-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20200805_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='consecutivo',
            field=models.CharField(default='1ff5eaf2076b', max_length=13),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
