# Generated by Django 3.0.7 on 2020-09-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_auto_20200902_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='shipping',
            name='consecutivo',
            field=models.CharField(default='881c14254d3f', max_length=13),
        ),
    ]
