# Generated by Django 3.0.7 on 2020-07-26 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200717_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 26, 3, 0, 31, 770348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysettings',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado/Activo'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
