# Generated by Django 3.0.7 on 2020-07-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200725_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='cel',
            field=models.CharField(max_length=100, verbose_name='Numero celular'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Numero contacto'),
        ),
    ]
