# Generated by Django 3.0.7 on 2020-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200723_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Telefono'),
        ),
    ]
