# Generated by Django 3.0.7 on 2020-07-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.IntegerField(verbose_name='Documento'),
        ),
    ]
