# Generated by Django 3.0.7 on 2020-07-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200731_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(max_length=980, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=12, null=True, verbose_name='Telefono'),
        ),
    ]
