# Generated by Django 3.0.7 on 2020-07-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0003_auto_20200722_1443'),
        ('customers', '0005_customer_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado/Activo')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado/Activo')),
                ('c_Tdocument', models.CharField(max_length=18, verbose_name='Tipo Documento')),
                ('c_document', models.IntegerField(verbose_name='Documento')),
                ('c_address', models.CharField(max_length=150)),
                ('c_phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('c_cel', models.IntegerField(verbose_name='Celular')),
                ('c_email', models.EmailField(max_length=100, verbose_name='Correo electronico')),
                ('shipping_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero guia')),
                ('photo', models.CharField(blank=True, max_length=1048576, null=True)),
                ('weight', models.CharField(blank=True, max_length=500, null=True, verbose_name='Peso')),
                ('send_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Bodega', 'Bodega'), ('Enviado', 'Enviado')], default='Bodega', max_length=7)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('c_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
                ('c_municipio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departamentos.Municipio')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Cliente')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.ShippingCompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
