# Generated by Django 3.0.7 on 2020-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre departamento'),
        ),
    ]
